version: '3.8'
services:

# For all the services mounted into a single container, you may need the following configs.
  mxshop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app

# For independent container for each microservice, you may need the following configs.
# Remember to your RPC callings via [service_name]:[service_port]
# e.g. client := client_stub.NewHelloServiceClient("tcp", "user_svc:9090")

#  user_api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./user_api:/app/user_api
#
#  user_svc:
#    build:
#      context: .
#      dockerfile: user_svc/docker/Dockerfile
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./user_svc:/app/user_svc

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ''
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'go-mysql:/var/lib/mysql'

volumes:
  go-mysql:
    driver: local
