services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - go-app

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ''
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'go-mysql:/var/lib/mysql'
    networks:
      - go-app

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'go-redis:/data'
    networks:
      - go-app
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

volumes:
  go-mysql:
    driver: local
  go-redis:
    driver: local

networks:
  go-app:
    driver: bridge