app:
  name: 'order_grpc_service'
  host: 'localhost'
  port: 50054
  env: 'local'
  debug: true

log:
  channel: 'single'

# Database
db:
  connection: 'mysql'
  host: 'localhost'
  port: 3307
  database: 'mxshop_order_svc'
  username: 'root'
  password: ''
  forward_password: ''

# Service discovery
sd:
  driver: 'consul' # local, consul, nacos

# Dynamic configuration
dc:
  driver: 'local' # local, nacos
  type: 'json' # json, yaml

consul:
  host: 'localhost'
  port: 8500
  service:
    tags:
      - 'mxshop'
      - 'order'
      - 'grpc'
    check:
      protocol: 'grpc'
      endpoint: 'host.docker.internal'
      interval: 10
      timeout: 5
      deregister_after: 1
nacos:
  server:
    host: "localhost"
    port: 8848
  client:
    namespace: "f5e80e5a-6596-40aa-a979-f194173966d5"
    username: ""
    password: ""
    data_id: "order_grpc"
    group: "LOCAL"
