app:
  name: 'order_grpc_service'
  host: 'localhost'
  port: 50054
  env: 'local'
  debug: true

log:
  channel: 'single'

# Database
db:
  connection: 'mysql'
  host: 'localhost'
  port: 3307
  database: 'mxshop_order_svc'
  username: 'root'
  password: ''
  forward_password: ''

# Service discovery
sd:
  driver: 'consul'

# Dynamic configuration
dc:
  driver: 'nacos'
  type: 'json'

consul:
  host: 'localhost'
  port: 8500
  service:
    name: 'order_grpc'
    tags:
      - 'mxshop'
      - 'order'
      - 'grpc'
    check:
      protocol: 'grpc'
      interval: 10
      timeout: 5
      deregister_after: 1
nacos:
  server:
    host: "localhost"
    port: 8848
  client:
    namespace: "e07b42ae-d767-44d2-83ea-f0bbe448c4dc"
    username: ""
    password: ""
    data_id: "order_grpc"
    group: "LOCAL"
